spring.application.name=PRODUCTO-SERVICE

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/db_productos
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=none
#muestra las consultas SQL en la consola
spring.jpa.show-sql=true
#formatea la salida de las consultas SQL para ver mejor la estructura 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Clave secreta usada para validar el token JWT
jwt.secret=clave_secreta_perfulandia_123456789_usuarios

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false

# Documentacion Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# URL donde esta publicado Eureka Server.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Registra este microservicio en Eureka al iniciar.
eureka.client.register-with-eureka=true

# Permite consultar el registro de servicios desde Eureka.
eureka.client.fetch-registry=true

# Publica preferentemente la IP del servicio en vez del hostname.
eureka.instance.prefer-ip-address=true
