spring.application.name=order-service-dev

#Driver usar para conectarse a la BD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Define cómo conectarse a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_pedidos

#Usuario BD
spring.datasource.username=root

#Pass BD
spring.datasource.password=system

#Estrategia de creación de tablas (none, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=validate

#Muestra en consola las consultas SQL que ejecuta Hibernate
spring.jpa.show-sql=true

#Formatear SQL consola
spring.jpa.properties.hibernate.format_sql=true

#Dialecto de Hibernate, le dice como generar el SQL para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Indica el puerto que usara el microservicio
server.port=8087

# Clave secreta usada para validar el token JWT
jwt.secret=clave_secreta_perfulandia_123456789_usuarios

# Activa Flyway para ejecutar migraciones SQL
spring.flyway.enabled=true

# Carpeta donde estan los archivos de migracion
spring.flyway.locations=classpath:db/migration

# Permite iniciar Flyway si la base ya existe
spring.flyway.baseline-on-migrate=true

# Valida que las migraciones no hayan cambiado
spring.flyway.validate-on-migrate=true

# URL del microservicio de productos
producto.service.url=http://localhost:8084
